version: '3.8'

services:
  app:
    build: .
    container_name: locadora_erp
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - .:/app
    device_cgroup_rules:
      - 'c 116:* rwm'
    privileged: true
