"""Add detailed vehicle and contract fields

Revision ID: 5a43358331a3
Revises: bfddba6bfd5a
Create Date: 2026-07-06 13:02:51.847146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a43358331a3'
down_revision: Union[str, Sequence[str], None] = 'bfddba6bfd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('valor_diaria', sa.Float(), nullable=False))
    op.add_column('contratos', sa.Column('desconto', sa.Float(), nullable=True))
    op.add_column('contratos', sa.Column('forma_pagamento', sa.String(length=50), nullable=True))
    op.add_column('contratos', sa.Column('seguro_incluso', sa.Boolean(), nullable=True))
    op.add_column('contratos', sa.Column('motorista_adicional', sa.String(length=150), nullable=True))
    op.add_column('contratos', sa.Column('checklist_json', sa.Text(), nullable=True))
    op.add_column('contratos', sa.Column('fotos_paths', sa.Text(), nullable=True))
    op.add_column('contratos', sa.Column('diarias_extras', sa.Integer(), nullable=True))
    op.add_column('contratos', sa.Column('avarias', sa.Text(), nullable=True))
    op.add_column('veiculos', sa.Column('cambio', sa.String(length=30), nullable=True))
    op.add_column('veiculos', sa.Column('portas', sa.Integer(), nullable=True))
    op.add_column('veiculos', sa.Column('capacidade', sa.Integer(), nullable=True))
    op.add_column('veiculos', sa.Column('valor_compra', sa.Float(), nullable=True))
    op.add_column('veiculos', sa.Column('valor_diaria', sa.Float(), nullable=True))
    op.add_column('veiculos', sa.Column('seguradora', sa.String(length=100), nullable=True))
    op.add_column('veiculos', sa.Column('apolice', sa.String(length=100), nullable=True))
    op.add_column('veiculos', sa.Column('fotos_paths', sa.Text(), nullable=True))
    op.add_column('veiculos', sa.Column('documentos_paths', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculos', 'documentos_paths')
    op.drop_column('veiculos', 'fotos_paths')
    op.drop_column('veiculos', 'apolice')
    op.drop_column('veiculos', 'seguradora')
    op.drop_column('veiculos', 'valor_diaria')
    op.drop_column('veiculos', 'valor_compra')
    op.drop_column('veiculos', 'capacidade')
    op.drop_column('veiculos', 'portas')
    op.drop_column('veiculos', 'cambio')
    op.drop_column('contratos', 'avarias')
    op.drop_column('contratos', 'diarias_extras')
    op.drop_column('contratos', 'fotos_paths')
    op.drop_column('contratos', 'checklist_json')
    op.drop_column('contratos', 'motorista_adicional')
    op.drop_column('contratos', 'seguro_incluso')
    op.drop_column('contratos', 'forma_pagamento')
    op.drop_column('contratos', 'desconto')
    op.drop_column('contratos', 'valor_diaria')
    # ### end Alembic commands ###
