"""Initial schema

Revision ID: bfddba6bfd5a
Revises: 
Create Date: 2026-07-06 12:18:21.031460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfddba6bfd5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('veiculos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('renavam', sa.String(length=20), nullable=True),
    sa.Column('chassi', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('ano_modelo', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('combustivel', sa.String(length=30), nullable=True),
    sa.Column('quilometragem', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('valor_fipe', sa.Float(), nullable=True),
    sa.Column('vencimento_seguro', sa.DateTime(), nullable=True),
    sa.Column('vencimento_ipva', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassi'),
    sa.UniqueConstraint('renavam')
    )
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('veiculo_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('caucao', sa.Float(), nullable=True),
    sa.Column('km_inicial', sa.Integer(), nullable=False),
    sa.Column('km_final', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('multas_adicionais', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_cliente_id'), 'contratos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contratos_veiculo_id'), 'contratos', ['veiculo_id'], unique=False)
    op.create_table('manutencoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('veiculo_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('fornecedor', sa.String(length=150), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_servico', sa.DateTime(), nullable=False),
    sa.Column('km_servico', sa.Integer(), nullable=False),
    sa.Column('proxima_revisao_km', sa.Integer(), nullable=True),
    sa.Column('proxima_revisao_data', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencoes_veiculo_id'), 'manutencoes', ['veiculo_id'], unique=False)
    op.create_table('lancamentos_financeiros',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('contrato_id', sa.String(), nullable=True),
    sa.Column('veiculo_id', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos_financeiros')
    op.drop_index(op.f('ix_manutencoes_veiculo_id'), table_name='manutencoes')
    op.drop_table('manutencoes')
    op.drop_index(op.f('ix_contratos_veiculo_id'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_cliente_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
